apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    name: mongo
    namespace: ${workspaceNamespace}
  name: mongo
  namespace: ${workspaceNamespace}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
