apiVersion: dataservices.nutanix.com/v1alpha1
kind: ProtectionPlan
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: pacman-protectionplan
  namespace: ${workspaceNamespace}
spec:
  scheduleName: hour-local-schedule
  retentionPolicy:
    retentionCount: 5
  replicationConfigs:
    - replicationTargetName: repln-target-dkp
