apiVersion: dataservices.nutanix.com/v1alpha1
kind: ProtectionPlan
metadata:
  name: pacman-protectionplan
  namespace: pacman
spec:
  scheduleName: hour-local-schedule
  retentionPolicy:
    retentionCount: 5
  replicationConfigs:
    - replicationTargetName: repln-target-dkp
